# Generated by Django 5.1 on 2024-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0005_alter_officenew_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('building_details', models.CharField(max_length=255)),
                ('rent_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='office_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='OfficeNew',
        ),
    ]
