# Generated by Django 5.1 on 2024-09-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0006_officedb_delete_officenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('cancellation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField()),
                ('satisfaction', models.CharField(choices=[('Good', 'Good'), ('Neutral', 'Neutral'), ('Not Satisfied', 'Not Satisfied')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_rented', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Officedb',
        ),
        migrations.AddField(
            model_name='meeting',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditapp.office'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditapp.office'),
        ),
        migrations.AddField(
            model_name='booking',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditapp.office'),
        ),
    ]
