# Generated by Django 5.1 on 2024-09-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0007_booking_customerfeedback_meeting_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetingnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
