# Generated by Django 5.1 on 2024-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0011_announcement_meetingroom_employee_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.CharField(default='General Office', max_length=255),
        ),
    ]
