# Generated by Django 5.1 on 2024-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0013_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('unique_users', models.IntegerField()),
                ('avg_time_spent', models.FloatField()),
            ],
        ),
    ]
