# Generated by Django 4.2.7 on 2024-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditapp', '0017_delete_analyticsdata_delete_announcement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governate', models.CharField(choices=[('muscat', 'Muscat'), ('dhofar', 'Dhofar'), ('musandam', 'Musandam'), ('al_batinah', 'Al Batinah'), ('al_dakhiliyah', 'Al Dakhiliyah'), ('buraymi', 'Buraymi'), ('batinah north', 'Al Batinah North'), ('batinah south', 'Al Batinah South'), ('al_wusta', 'Al Wusta'), ('ash_sharqiyah north', 'Ash Sharqiyah North'), ('ash_sharqiyah south', 'ash_sharqiyah south')], max_length=100)),
                ('wilayat', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=200)),
                ('head_of_institution', models.CharField(max_length=200)),
                ('rationale', models.CharField(choices=[('annual_assessment', 'Annual Assessment'), ('complaint_investigation', 'Complaint Investigation'), ('quality_control', 'Quality Control'), ('follow_up_visit', 'Follow-up Visit')], max_length=100)),
            ],
        ),
    ]
