# Generated by Django 4.2.7 on 2024-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0018_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governate', models.CharField(max_length=100)),
                ('wilayat', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=255)),
                ('head_of_institution', models.CharField(max_length=255)),
                ('rationale', models.CharField(max_length=100)),
                ('audit_date', models.DateField()),
                ('lead_auditor', models.CharField(max_length=255)),
                ('auditors', models.TextField()),
                ('areas_covered', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
