# Generated by Django 4.2.7 on 2024-09-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0019_facilityaudit_delete_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('scoring', models.CharField(choices=[('NA', 'Not Applicable'), ('Met', 'Met'), ('Partially Met', 'Partially Met'), ('Not Met', 'Not Met')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
