# Generated by Django 4.1 on 2024-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0020_ipcprogram"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("ref_no", models.CharField(max_length=10)),
                ("description", models.TextField()),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("Met", "Met"),
                            ("Partially Met", "Partially Met"),
                            ("Not Met", "Not Met"),
                        ],
                        max_length=20,
                    ),
                ),
                ("audit_date", models.DateField(auto_now_add=True)),
                ("facility_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AuditSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("met_count", models.IntegerField(default=0)),
                ("partially_met_count", models.IntegerField(default=0)),
                ("not_met_count", models.IntegerField(default=0)),
                ("comments", models.TextField(blank=True, null=True)),
                ("audit_date", models.DateField(auto_now_add=True)),
                ("facility_name", models.CharField(max_length=100)),
            ],
        ),
    ]
