# Generated by Django 4.1 on 2024-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0021_auditresponse_auditsummary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditsummary",
            name="audit_date",
        ),
        migrations.RemoveField(
            model_name="auditsummary",
            name="facility_name",
        ),
    ]
