# Generated by Django 4.1 on 2024-10-23 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0022_remove_auditsummary_audit_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditresponse",
            name="facility_name",
        ),
    ]
