# Generated by Django 4.1 on 2024-10-23 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0023_remove_auditresponse_facility_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuditResponse",
            new_name="AuditResponsenew",
        ),
    ]
