# Generated by Django 4.1 on 2024-10-23 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0024_rename_auditresponse_auditresponsenew"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilityaudit",
            name="facility_name",
        ),
    ]
