# Generated by Django 4.1 on 2024-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0025_remove_facilityaudit_facility_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityAuditnew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(max_length=255)),
                ("governate", models.CharField(max_length=100)),
                ("wilayat", models.CharField(max_length=100)),
                ("head_of_institution", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=100)),
                ("audit_date", models.DateField()),
                ("lead_auditor", models.CharField(max_length=255)),
                ("auditors", models.TextField()),
                ("areas_covered", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="FacilityAudit",
        ),
    ]
