# Generated by Django 4.1 on 2024-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0026_facilityauditnew_delete_facilityaudit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opp_number", models.IntegerField(default=1)),
            ],
        ),
    ]
