# Generated by Django 4.1 on 2024-11-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0027_opportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditsummary",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="audit_photos/"),
        ),
    ]
