# Generated by Django 4.1 on 2024-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditapp", "0028_auditsummary_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.IntegerField()),
                ("opp_hr", models.IntegerField(default=0)),
                ("act_hr", models.IntegerField(default=0)),
                ("opp_hw", models.IntegerField(default=0)),
                ("act_hw", models.IntegerField(default=0)),
            ],
        ),
    ]
